version: '3'
services:
  # service名
  app:
    # イメージ名
    image: kasegi-backend
    environment:
      - ENV=stg
      - GoogleClientID=$GoogleClientID
      - googleClientSecret=$googleClientSecret
      - TokenEndpoint=$TokenEndpoint
      - AuthorizeEndpoint=$AuthorizeEndpoint
      - dbServerUrl=$dbServerUrl
      - dbServerPort=$dbServerPort
      - dbServerUserId=$dbServerUserId
      - dbServerPs=$dbServerPs
    # ビルドに使用するDockerfileがあるディレクトリ指定
    build: .
    ports:
      - "80:8080"