// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_psql

var TableNames = struct {
	GameMatches      string
	GameTitles       string
	SchemaMigrations string
	Users            string
}{
	GameMatches:      "game_matches",
	GameTitles:       "game_titles",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
