// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChecklistTemplateItems  string
	ChecklistTemplates      string
	GameMatchChecklistItems string
	GameMatches             string
	GameTitles              string
	LoginSessions           string
	SchemaMigrations        string
	Users                   string
}{
	ChecklistTemplateItems:  "checklist_template_items",
	ChecklistTemplates:      "checklist_templates",
	GameMatchChecklistItems: "game_match_checklist_items",
	GameMatches:             "game_matches",
	GameTitles:              "game_titles",
	LoginSessions:           "login_sessions",
	SchemaMigrations:        "schema_migrations",
	Users:                   "users",
}
