// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GameMatchSelectionItems string
	GameMatches             string
	GameTitles              string
	LoginSessions           string
	SchemaMigrations        string
	Users                   string
}{
	GameMatchSelectionItems: "game_match_selection_items",
	GameMatches:             "game_matches",
	GameTitles:              "game_titles",
	LoginSessions:           "login_sessions",
	SchemaMigrations:        "schema_migrations",
	Users:                   "users",
}
