// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GameMatches      string
	GameTitles       string
	LoginSessions    string
	SchemaMigrations string
	Users            string
}{
	GameMatches:      "game_matches",
	GameTitles:       "game_titles",
	LoginSessions:    "login_sessions",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
